String get getTransactionQuery => '''
query getTransancationDetails(\$options:TransactionSearchInput!){
  getTransactions(options:\$options){
  ... on TransactionResponse{
    Transactions{
      customerName
      customerPhNo
      lastFourDigit
      transactionId
      refundTransactionId
      associatedTransactionId
      merchantName
      mcc
      refundId
      transactionDate
      refundTransactionDate
      transactionType
      totalTransactionAmount{
        amount
        currency
      }
      orderId
      associatedOrderId
      transactionCategory
      status
      totalRefundAmount
      processingFee
      discount
      vat
      balanceAfter{
        amount
        currency
      }
      balanceBefore{
        amount
        currency
      }
      cardNickName
      brandName
      remarks
      originalTransaction{
          transactionId
          merchantName
          mcc
          remarks
          refundId
          transactionDate
          transactionType
          totalTransactionAmount{
            amount
            currency
          }
          balanceAfter{
            amount
            currency
          }
          balanceBefore{
            amount
            currency
          }
          refundTransactionDate
          refundTransactionId
          totalRefundAmount
          associatedOrderId
          transactionsAmount
          orderId
          transactionCategory
          status
          processingFee
          discount
          vat
        }
      }
    }
    ... on Error{
      message
      status
    }
  }
}
''';
