name: crayon_payment_customer
description: CrayonPayment Customer Base App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.12.0
  json_serializable: ^6.1.4
  flutter_riverpod: ^1.0.3
  carousel_slider: ^4.0.0
  syncfusion_flutter_datepicker: ^19.4.53
  get: ^4.6.1
  image_cropper: ^1.5.0
  screenshot: ^1.2.3
  share: ^2.0.4
  path_provider: ^2.0.9
  image_gallery_saver: '^1.7.1'
  contacts_service: ^0.6.3
  permission_handler: ^9.1.0
  connectivity_for_web: 0.4.0+1
  scan: ^1.6.0
  sqflite:

  config:
    path: ../customer/config

  core:
    path: ../../libs/core/

  network_manager:
    path: ../../libs/network-manager/

  task_manager:
    path: ../../libs/task-manager/

  shared_data_models:
    path: ../../libs/shared-data-models/

  widget_library:
    path: ../../libs/widgets/

  welcome:
    path: ../../libs/features/welcome

  passcode:
    path:  ../../libs/features/passcode

  agent_nearby:
    path: ../../libs/features/agent_nearby

  device_option:
    path: ../../libs/features/device_option

  login:
    path: ../../libs/features/login


dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  pedantic: ^1.11.1
  dart_code_metrics: ^4.11.0
  build_runner:
  dartz: ^0.10.1


flutter:
  uses-material-design: true
  assets:
    - assets/configuration/network_configuration_dev.json
    - assets/styles/
    - assets/configuration/network_config.json
    - assets/lang/
    - assets/images/
    - assets/welcomeback/
    - assets/home/
    - assets/configuration/static_auth.json


  fonts:
    - family: Brown
      fonts:
        - asset: assets/fonts/Brown-Regular.ttf
    - family: Brown-Light
      fonts:
        - asset: assets/fonts/Brown-Light.ttf
    - family: Zarid-Medium
      fonts:
        - asset: assets/fonts/Zarid-Medium.otf
    - family: OCR-A
      fonts:
        - asset: assets/fonts/OCR-A-Regular.ttf
    - family : Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
