name: crayon_payment_customer
description: CrayonPayment Customer Base App
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.4
  flutter_riverpod: ^1.0.3
  carousel_slider: ^4.0.0
  get: ^4.6.1
  sqflite:

  config:
    path: ../../config


  crayon_payment_agent:
    path: ../agent/

  core:
    path: ../../libs/core/

  network_manager:
    path: ../../libs/network-manager/

  task_manager:
    path: ../../libs/task-manager/

  shared_data_models:
    path: ../../libs/shared-data-models/

  widget_library:
    path: ../../libs/widgets/

  welcome:
    path: ../../libs/features/welcome

  passcode:
    path:  ../../libs/features/passcode

  agent_nearby:
    path: ../../libs/features/agent_nearby

  device_option:
    path: ../../libs/features/device_option

  login:
    path: ../../libs/features/login

  verifyotp:
    path: ../../libs/features/verifyotp

  splash:
    path: ../../libs/features/splash

  home:
    path: ../../libs/features/home

  termscondition:
    path: ../../libs/features/termscondition

  settings:
    path: ../../libs/features/settings

  payments:
    path: ../../libs/features/payments


dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  pedantic: ^1.11.1
  dart_code_metrics: ^4.11.0
  build_runner:
  dartz: ^0.10.1
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/applogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/configuration/network_configuration_dev.json
    - assets/styles/
    - assets/configuration/network_config.json
    - assets/lang/
    - assets/images/
    - assets/deviceoption/
    - assets/welcomeback/
    - assets/home/
    - assets/configuration/static_auth.json


  fonts:
    - family : Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
