const HS_NotificationIcon = 'assets/home/notification_icon.png';
const HS_LoadWalletIcon = 'assets/home/add_icon.png';
const HS_SendMoneyIcon = 'assets/home/arrow_forward_icon.png';
const String HS_LoanRepaymentIcon = 'assets/home/arrow_backward.png';
const String HS_LoanRepayment1Icon = 'assets/home/countdown_icon.png';
const String HS_InviteIcon = 'assets/home/invite_icon.png';
const String HS_HomeIcon = 'assets/home/home_icon.png';
const String HS_SettingIcon = 'assets/home/setting_icon.png';
const String HS_ScanIcon = 'assets/home/scan_icon.png';
