name: crayon_payment_agent
description: CrayonPayment Agent Base App
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^6.1.4
  flutter_riverpod: ^1.0.3
  carousel_slider: ^4.0.0
  syncfusion_flutter_datepicker: ^19.4.53
  get: ^4.6.1
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9




  config:
    path: ../../config

  core:
    path: ../../libs/core/

  network_manager:
    path: ../../libs/network-manager/

  task_manager:
    path: ../../libs/task-manager/

  widget_library:
    path: ../../libs/widgets/

  welcome:
    path: ../../libs/features/welcome

  passcode:
    path: ../../libs/features/passcode

  agent_nearby:
    path: ../../libs/features/agent_nearby

  device_option:
    path: ../../libs/features/device_option

  login:
    path: ../../libs/features/login

  verifyotp:
    path: ../../libs/features/verifyotp

  splash:
    path: ../../libs/features/splash

  home:
    path: ../../libs/features/home

  settings:
    path: ../../libs/features/settings

  termscondition:
    path: ../../libs/features/termscondition

  kyc:
    path: ../../libs/features/kyc

  loan_details:
    path: ../../libs/features/loan_details

  downpayment:
    path: ../../libs/features/downpayment



dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.11.1
  dart_code_metrics: ^4.11.0
  build_runner:
  flutter_launcher_icons:



flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/applogo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/configuration/network_configuration_dev.json
    - assets/lang/
    - assets/styles/
    - assets/images/
    - assets/home/
    - assets/configuration/network_config.json
    - assets/configuration/static_auth.json

  fonts:

    - family : Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
